name: Test Action

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ensure build is working correctly
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i
          npm run build:pack
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    name: Ensure action works on a clean machine without building
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
